companieshouse/psc-filing-api

- docs/PSC Filing API.postman_collection.json
> remove double underscore from filing_resource_id

- src/main/java/uk/gov/companieshouse/pscfiling/api/error/RestExceptionHandler.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/model/dto/PscCommonDto.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/model/dto/PscDtoCommunal.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/model/dto/PscIndividualDto.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/error/RestExceptionHandlerTest.java
- remove Java exception class details from messages
  - keep messages clear and concise
  - improve validation when date ranges exceeded
- add missing test coverage
PSC-27
> Add basic data validation (PSC07)

- src/main/java/uk/gov/companieshouse/pscfiling/api/model/entity/PscIndividualFiling.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/FilingDataControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImplTest.java
- to be consistent with other collection names as agreed with Mike
- also small refactor to use FilingKind constant
> Rename collection to 'psc_submissions'

- src/main/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImplTest.java
https://companieshouse.atlassian.net/browse/PSC-83
> Resolves: PSC-83

- src/main/java/uk/gov/companieshouse/pscfiling/api/mapper/PscIndividualMapper.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/model/dto/FilingDataDto.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImplTest.java
https://companieshouse.atlassian.net/browse/PSC-14
> Resolves: PSC-14

- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplTest.java
Please check that transactions are prevented when the feature flag for 'transactions closable' is set to 'false' and allowed when set to 'true'.
> Transaction is closed even when feature flag for 'transactions closable' is set to false

- docs/PSC Filing API.postman_collection.json
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagFalseIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagNotBooleanIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagTrueIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagUndefinedIT.java
PSC-111
Removed 'private' from endpoint. Itegration Tests updated to reflect new endpoint and all working in Postman.
> Make validation-status endpoint public

- pom.xml
- src/main/java/uk/gov/companieshouse/pscfiling/api/config/ValidatorConfig.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/PscRegisterEntryDateValidator.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/config/ValidatorConfigTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/validator/PscRegisterEntryDateValidatorTest.java
Validator created to check the register entry date is not before the cessation date.
> Add register entry date validation

- src/main/java/uk/gov/companieshouse/pscfiling/api/config/ValidatorConfig.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/mapper/ErrorMapper.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/CeasedOnDateValidator.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/PscFilingApiApplicationTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/config/IntegrationTestConfig.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagFalseIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagNotBooleanIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagTrueIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagUndefinedIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplValidationIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/mapper/ErrorMapperTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/validator/CeasedOnDateValidatorTest.java
Apply existing validation rules for '/validation_status' endpoint requests
PSC-28
PSC-29
PSC-30
PSC-39
PSC-112
> Apply validations on validation_status endpoint requests

- pom.xml
- src/main/java/uk/gov/companieshouse/pscfiling/api/config/InterceptorConfig.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/pscfiling/api/config/InterceptorConfigTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/BaseControllerIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PermissionInterceptorIT.java
- requires api-security-java v0.4 (see PR #34)
> Add permissions interceptor with PSC07 permissions

- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/FilingDataController.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/FilingDataControllerImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingController.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingController.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusController.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/FilingDataControllerImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/FilingDataControllerTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagFalseIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagNotBooleanIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagTrueIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplFlagUndefinedIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerImplValidationIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/ValidationStatusControllerTest.java
Replace transaction call with transaction request attribute.
https://companieshouse.atlassian.net/browse/PSC-132
> Resolves: PSC-132

- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImpl.java
Omitted to remove method from child class that had been moved to parent
> Sonar issue - remove method from child class

- src/main/java/uk/gov/companieshouse/pscfiling/api/config/ValidatorConfig.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/service/PscDetailsServiceImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/BaseFilingValidator.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/CeasedOnDateValidator.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/FilingForPscTypeValid.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/FilingForPscTypeValidChain.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/FilingValid.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/PscEtagValidator.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/PscExistsValidator.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/PscIsActiveValidator.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/PscRegisterEntryDateValidator.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/validator/TerminationRequiredFieldsValidator.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/config/ValidatorConfigTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/service/FilingValidationServiceImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/service/PscDetailsServiceImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/validator/FilingForPscTypeValidChainTest.java
- also renamed BaseValidator and FilingValid interface to not say 'Individual'
PSC-74
PSC-75
> Add validation chains for Corporate and Legal Person PSC types

- src/main/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/service/FilingDataServiceImplTest.java
Pass the PSC type to chips in the filings
`"kind": "psc-filing#cessation#individual"`
PSC-77
PSC-78
> Pass the PSC type to chips in the filings

- src/main/java/uk/gov/companieshouse/pscfiling/api/PscFilingApiApplication.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/config/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/interceptor/RequestLoggingInterceptor.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/config/InterceptorConfigTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/interceptor/RequestLoggingInterceptorTest.java
- Add logging interceptor
https://companieshouse.atlassian.net/browse/PSC-140
> Resolves: PSC-140

- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImplTest.java
> Add created_at field for all PSC types in POST request

- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscIndividualFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/PscWithIdentificationFilingControllerImplTest.java
> Bug Fix: updated_at not showing in POST response

- README.md
> Add content for README

- docs/Validation Class Structure.puml
Implements the 'chain of responsibility' design pattern
> Class diagram for the validation

- src/main/java/uk/gov/companieshouse/pscfiling/api/error/RestExceptionHandler.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/exception/MergePatchException.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/interceptor/CompanyInterceptor.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/service/impl/PscIndividualFilingServiceImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/service/impl/PscWithIdentificationFilingServiceImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscIndividualFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscIndividualFilingControllerImplMergeIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscWithIdentificationFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscWithIdentificationFilingControllerImplMergeIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/error/RestExceptionHandlerTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/interceptor/CompanyInterceptorTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/service/impl/PscIndividualFilingServiceImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/service/impl/PscWithIdentificationFilingServiceImplTest.java
PSC-231
Requires PR companieshouse/api-enumerations#191
> Updates for messages to conform to API Enumerations

- src/main/java/uk/gov/companieshouse/pscfiling/api/config/AppConfig.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscIndividualFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscWithIdentificationFilingControllerImplIT.java
> Add Unrecognised Property error to POST responses

- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscIndividualFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscWithIdentificationFilingControllerImpl.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscIndividualFilingControllerImplMergeIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscIndividualFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscWithIdentificationFilingControllerImplMergeIT.java
- src/test/java/uk/gov/companieshouse/pscfiling/api/controller/impl/PscWithIdentificationFilingControllerImplTest.java
> Bugfix: Patch 404 response has empty JSON body

- docs/PATCH Service Schematic.puml
- docs/Patch Service Schematic Implementation for PSCIndividuaFiling.puml
- docs/Patch Service Schematic Implementation for PscWithIdentificationFiling.puml
Patch service schematic and implementation of schematic for the PscIndividualFiling and PscWithIdentificationFIling
> Add UML diagrams for PATCH service

- docs/PSC Filing API.postman_collection.json
The Postman collection has been updated so that it can be run locally in Docker or with TCats1 using the Atlas MongoDB instance.
> Update Postman collection for PSC07

- pom.xml
- src/main/java/uk/gov/companieshouse/pscfiling/api/PscFilingApiApplication.java
- src/main/java/uk/gov/companieshouse/pscfiling/api/interceptor/RequestLoggingInterceptor.java
fix: new vulnerability in spring-web & application name space mismatch found in pipeline issues
> Vulnerability upgrades and namespace change

- README.md
psc-filing-api
adding ecs information to the README
> JU-778 adding ecs info to README

- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
- terraform/groups/ecs-service/variables.tf
**Jira ticket**: 
>
> Use screenshots or logs to show what your changes do.
>
> Add test notes only if they're **not** already included in the Jira ticket.
Strikethrough (`~~like this~~`) anything not applicable to your changes.
> Tech debt changes

- pom.xml
**Jira ticket**: ASM-292
add `<sonar.token>${CODE_ANALYSIS_TOKEN}</sonar.token>` as per guidance
Pipeline change ready - https://github.com/companieshouse/ci-pipelines/pull/5343
> Move to sonarqube.companieshouse.gov.uk
